exclude:
  - checkout/
  - watch
  - bake_images
  - README.md
  - pybrew
  - .cache
  - node_modules

# Dynamic params
baseurl: /
branch-prefix: 
github-repo:
github-branch:
github-commit-sha: 
no-index: false

# Regular params
title: Flow Brew
email: ak@flowbrew.ru

products:
  matcha:
    id: flowbrew60
    price: 3880
    currency: "RUB"
    shipping: 100
    fast_shiping: 1100
    weight: 60
    quantity: 4

plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

sass:
  style: compressed
  load_paths:
      - _sass
      - node_modules

permalink: /blog/:title
  
footer:
  contacts: контакты
  shipment: доставка
  payment: оплата
  privacypolicy: политика конфиденциальности
  refund: гарантии и возврат
  signature: © 2019, Flow Brew
  blog: блог
  shop: магазин чая матча
