#!/bin/bash

echo "---> Deploy Jekyll"

# Configure credentials
aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
${AWS_ACCESS_KEY_ID}
${AWS_SECRET_ACCESS_KEY}
${AWS_REGION}
text
EOF

# Creating a bucket
aws s3 mb s3://${AWS_S3_BUCKET} \
    --profile s3-sync-action
aws s3 website s3://${AWS_S3_BUCKET} \
    --profile s3-sync-action \
    --index-document index.html \
    --error-document 404.html

# Actual deploying
aws s3 sync ${SOURCE_DIR:-.} s3://${AWS_S3_BUCKET}/${TARGET_DIR} \
    --profile s3-sync-action \
    --no-progress \
    --acl public-read --follow-symlinks --delete

# Cleaning credentials
aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
null
null
null
text
EOF