name: CI/CD

on:
  push:
    branches:
      - "*"
  delete:
    branches:
      - "*"
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1
      - uses: actions/checkout@v2
      - name: CI/CD
        env:
          GITHUB_WEBSITE_USERNAME: ${{ secrets.GITHUB_WEBSITE_USERNAME }}
          GITHUB_WEBSITE_TOKEN: ${{ secrets.GITHUB_WEBSITE_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          TINIFY_KEY: ${{ secrets.TINIFY_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GOOGLE_PAGESPEED_KEY: ${{ secrets.GOOGLE_PAGESPEED_KEY }}
          YANDEX_BOT_EMAIL: ${{ secrets.YANDEX_BOT_EMAIL }}
          YANDEX_BOT_TOKEN: ${{ secrets.YANDEX_BOT_TOKEN }}
          GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
        run: |
          ./cicd \
            ${{ github.workflow }} \
            ${{ github.event_name }} \
            ${{ github.event.ref }}

  pre-split-test-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_WEBSITE_USERNAME: ${{ secrets.GITHUB_WEBSITE_USERNAME }}
          GITHUB_WEBSITE_TOKEN: ${{ secrets.GITHUB_WEBSITE_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
        run: |
          ./cicd \
            ${{ github.workflow }} \
            pre_split_test_analysis \
            ${{ github.event.ref }}
