name: Cleanup Branch

on: [delete]

env:
  WEBSITE_REPO: flowbrew/website-deployment

jobs:
  cleanup:
    runs-on: ubuntu-latest
    container: 
      image: ntoss/builder:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Ckeanup Jekyll
        run: |
          pip install path
          .github/workflows/scripts/cleanup.py \
              -t ${{ secrets.GITHUB_WEBSITE_TOKEN }} \
              -u ${{ secrets.GITHUB_WEBSITE_USERNAME }} \
              -r ${{ env.WEBSITE_REPO }} \
              -b ${{ github.event.ref }}

      - name: Notify success cleanup
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{
            \"channel\": \"${{ secrets.SLACK_BOT_CHANNEL }}\",
            \"text\": \"Successfully cleanup 🧹 branch ${{ github.event.ref }}\"
            }'

      - name: Notify failed cleanup
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{
            \"channel\": \"${{ secrets.SLACK_BOT_CHANNEL }}\",
            \"text\": \"FAILED 😡 to 🧹 cleanup branch ${{ github.event.ref }}\"
            }'
