name: Cleanup Branch

on: [delete]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    container: 
      image: python:3.7
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # - name: Delete bucket
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ${{ secrets.AWS_REGION }}
      #     AWS_S3_BUCKET: ${{ github.event.ref }}.${{ secrets.DOMAIN }}
      #   run: .github/workflows/scripts/cleanup
