name: Cleanup Branch

on: [delete]

env:
  WEBSITE_REPO: flowbrew/website-deployment

jobs:
  cleanup:
    runs-on: ubuntu-latest
    container: 
      image: ntoss/builder:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install pybrew
        run: |
          pip install ./pybrew
          pytest --pyargs pybrew \
            --SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}

      - name: Ckeanup Jekyll
        run: |
          .github/workflows/scripts/cleanup.py \
              -t ${{ secrets.GITHUB_WEBSITE_TOKEN }} \
              -u ${{ secrets.GITHUB_WEBSITE_USERNAME }} \
              -r ${{ env.WEBSITE_REPO }} \
              -b ${{ github.event.ref }}

      - name: Notify success build
        shell: python
        run: |
          import pybrew
          notification(
            channel='#website',
            text='Successfully cleanup 🧹 branch ${{ github.event.ref }}',
            token=${{ secrets.SLACK_BOT_TOKEN }}
            )

      - name: Notify failed build
        if: failure()
        shell: python
        run: |
          import pybrew
          notification(
            channel='#website',
            text='FAILED 😡 to 🧹 cleanup branch ${{ github.event.ref }}}',
            token=${{ secrets.SLACK_BOT_TOKEN }}
            )
