name: Cleanup Branch

on: [delete]

env:
  WEBSITE_REPO: flowbrew/website-deployment
  SCRIPTS_PATH: .github/workflows/scripts
  BRANCH_NAME: ${{ github.event.ref }}
  REPOSITORY: ${{ github.repository }}
  WORKFLOW: ${{ github.workflow }}
  EVENT_NAME: ${{ github.event_name }}
  HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  HEAD_COMMIT_URL: ${{ github.event.head_commit.url }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    container: 
      image: ntoss/builder:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install pybrew
        run: |
          pip install ./pybrew
          pytest --color=yes --pyargs pybrew \
            --SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}

      - name: Ckeanup Jekyll
        run: |
          .github/workflows/scripts/cleanup.py \
              -t ${{ secrets.GITHUB_WEBSITE_TOKEN }} \
              -u ${{ secrets.GITHUB_WEBSITE_USERNAME }} \
              -r ${{ env.WEBSITE_REPO }} \
              -b ${{ env.BRANCH_NAME }}

      - name: Notify
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
          SECRET_SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: ${{ env.SCRIPTS_PATH }}/notifier.py
