name: Cleanup Branch

on: [delete]

env:
  TEST_REPOSITORY: test-website-deployment
  TARGET_REPOSITORY: website-deployment

jobs:
  cleanup:
    runs-on: ubuntu-latest
    container:
      image: ntoss/builder:latest
    steps:
      - run: |
          git config --global user.email "action@flowbrew.ru"
          git config --global user.name "GitHub Action"
      - uses: actions/checkout@v1
      - run: pip install ./pybrew

      - name: Cleanup
        shell: python
        run: |
          from pybrew import cleanup_io
          cleanup_io(
              github_username='${{ secrets.GITHUB_WEBSITE_USERNAME }}',
              github_token='${{ secrets.GITHUB_WEBSITE_TOKEN }}',
              organization='${{ github.event.organization.login }}',
              target_repo_name='${{ env.TARGET_REPOSITORY }}',
              slack_token='${{ secrets.SLACK_BOT_TOKEN }}',
              branch='${{ github.event.ref }}',
              workflow='${{ github.workflow }}',
              head_commit_message='${{ github.event.head_commit.message }}',
              head_commit_url='${{ github.event.head_commit.url }}',
              event_name='${{ github.event_name }}',
          )
