name: CICD

on: [push]

env:
  DOMAIN: flowbrew.ru
  ORGANIZATION: ${{ github.event.organization.login }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  WEBSITE_REPO: flowbrew/website-deployment
  SCRIPTS_PATH: .github/workflows/scripts
  REPOSITORY: ${{ github.repository }}
  WORKFLOW: ${{ github.workflow }}
  EVENT_NAME: ${{ github.event_name }}
  HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  HEAD_COMMIT_URL: ${{ github.event.head_commit.url }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: ntoss/builder:latest
    env:
      BUILD_PATH: ./_site
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      # Saving branch name to ${BRANCH_NAME}
      - uses: nelonoel/branch-name@v1

      - uses: actions/checkout@v1
      - name: Install pybrew
        run: |
          pip install requests
          pip install ./pybrew
          pytest -vv --color=yes --pyargs pybrew \
            --runslow \
            --SECRET_SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }} \
            --SECRET_GITHUB_WEBSITE_USERNAME=${{secrets.GITHUB_WEBSITE_USERNAME}} \
            --SECRET_GITHUB_WEBSITE_TOKEN=${{secrets.GITHUB_WEBSITE_TOKEN}}

      - name: Build Jekyll
        run: |
          ${{ env.SCRIPTS_PATH }}/build.py \
              -d ${{ env.BUILD_PATH }} \
              -r ${{ github.repository }} \
              -S ${{ github.sha }} \
              -b ${{ env.BRANCH_NAME }}

      - name: Deploy Jekyll
        shell: python
        run: |
          from pybrew import \
            deploy_to_github_io, url_, wait_until_deployed_by_sha_io

          deploy_to_github_io(
              username: '${{ secrets.GITHUB_WEBSITE_USERNAME }}',
              token: '${{ secrets.GITHUB_WEBSITE_TOKEN }}',
              organization: '${{ env.ORGANIZATION }}',
              repo_name: '${{ env.REPOSITORY_NAME }}',
              branch: '${{ env.BRANCH_NAME }}',
              path: '${{ env.BUILD_PATH }}',
          )

          wait_until_deployed_by_sha_io(
              url_('${{ env.DOMAIN }}', '${{ env.BRANCH_NAME }}', ''),
              sha
          )

      - name: Notify
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
          SECRET_SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: ${{ env.SCRIPTS_PATH }}/notifier.py
