name: CICD

on: [push]

env:
  WEBSITE_REPO: flowbrew/website-deployment

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: 
      image: ntoss/builder:latest
    env:
      BUILD_PATH: ./_site
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      # Saving branch name to ${BRANCH_NAME}
      - uses: nelonoel/branch-name@v1

      - uses: actions/checkout@v1
      - name: Install pybrew
        run: |
          pip install ./pybrew
          pytest --pyargs pybrew \
            --SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}

      - name: Build Jekyll
        run: |
          .github/workflows/scripts/build.py \
              -d ${{ env.BUILD_PATH }} \
              -r ${{ github.repository }} \
              -S ${{ github.sha }} \
              -b ${{ env.BRANCH_NAME }}

      - name: Deploy Jekyll
        run: |
          .github/workflows/scripts/deploy.py \
              -t ${{ secrets.GITHUB_WEBSITE_TOKEN }} \
              -u ${{ secrets.GITHUB_WEBSITE_USERNAME }} \
              -r ${{ env.WEBSITE_REPO }} \
              -s ${{ env.BUILD_PATH }} \
              -S ${{ github.sha }} \
              -b ${{ env.BRANCH_NAME }}

      - name: Notify success build
        shell: python
        run: |
          from pybrew import *
          notification(
            channel='#website',
            text='Successfully ✅ deployed branch ${{ env.BRANCH_NAME }}',
            token='${{ secrets.SLACK_BOT_TOKEN }}'
            )

      - name: Notify failed build
        if: failure()
        shell: python
        run: |
          from pybrew import *
          notification(
            channel='#website',
            text='FAILED 😡 to deploy branch ${{ env.BRANCH_NAME }}',
            token='${{ secrets.SLACK_BOT_TOKEN }}'
            )
