name: CI/CD

on: [push]

env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_WEBSITE_TOKEN }}
  MY_GITHUB_ORGANIZATION: flowbrew
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terramorf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run a Terraform init
        uses: docker://hashicorp/terraform:0.12.19
        with:
          entrypoint: terraform
          args: init

      - name: Run a Terraform validate
        uses: docker://hashicorp/terraform:0.12.19
        with:
          entrypoint: terraform
          args: validate

      - name: Run a Terraform apply
        uses: docker://hashicorp/terraform:0.12.19
        with:
          entrypoint: terraform
          args: apply

